## This is an Invoice Practice Sample

In [1]:


A = ("Welcome to ASOROCK PLACE")
A1 = ("EXECUTIVE EATERY")
A2 =  ("IKEJA AIRPORT HOTEL")
A3 = ("IKEJA")
A4 = ("LAGOS STATE")
A5 = ("=========================================")
A6 = ("Qty  Description                   Extend")
A7 = ("-----------------------------------------")
A8 = int(1) 
A9 = int(1)
A10 = int(1)
A11 = int(1)
A12 = int(2)
A13 = int(2)
A14 = int(8)

A10_name = ("Coconut Rice")
A11_name = ("Chicken")
A12_name = ("Bottle Water")
A13_name = ("Boiled or fried Plantain")
A14_name = ("Chapman")
A15_name = ("Take away Plate")
A16_name = ("Subtotal")
A17_name = ("Total")
A18_name = ("PaidCash")
A19_name = ("Products")

A1_price = 2812.00
A2_price = 2812.00
A3_price = 337
A4_price = 1130.00
A5_price = 4500.00
A6_price = 400
A7_price = A1_price + A2_price + A3_price + A4_price + A5_price + A6_price
A8_price = A1_price + A2_price + A3_price + A4_price + A5_price + A6_price
A9_price = A1_price + A2_price + A3_price + A4_price + A5_price + A6_price 



print(A)
print(A1)
print(A2)
print(A3)
print(A4)
print(A5)
print(A6)
print(A7)
print(str(A8)+ ' ' +A10_name + '                        ' + str(A1_price))
print(str(A9)+ ' ' +A11_name + '                             ' + str(A2_price))
print(str(A10)+ ' '+A12_name + '                        ' + str(A3_price))
print(str(A11)+ ' ' +A13_name + '            ' + str(A4_price))
print(str(A12)+ ' ' +A14_name + '                             ' + str(A5_price))
print(str(A13)+ ' ' +A15_name + '                     ' + str(A6_price))

print('                    '+ A16_name +'         '+  str(A7_price))
print('                    '+ A17_name +'            '+  str(A8_price))
print('                    '+A18_name +'         '+  str(A9_price))


print("Receipts#   169977")
print("Products:   " + str(A14))
print("Date:  3/21/2023,  8:40pm.")
print("Cashier:  Buhari")
print("Thank you for your patronage.")
print("Kindly visit us again for that awesome taste.")
print("081735195190")
print(A7)

Welcome to ASOROCK PLACE
EXECUTIVE EATERY
IKEJA AIRPORT HOTEL
IKEJA
LAGOS STATE
=========================================
Qty  Description                   Extend
-----------------------------------------
1 Coconut Rice                        2812.0
1 Chicken                             2812.0
1 Bottle Water                        337
1 Boiled or fried Plantain            1130.0
2 Chapman                             4500.0
2 Take away Plate                     400
                    Subtotal         11991.0
                    Total            11991.0
                    PaidCash         11991.0
Receipts#   169977
Products:   8
Date:  3/21/2023,  8:40pm.
Cashier:  Buhari
Thank you for your patronage.
Kindly visit us again for that awesome taste.
081735195190
-----------------------------------------